version: "2.1"

networks:
  traefik:
    external: true

services:
  grocy:
    image: linuxserver/grocy:3.3.2
    container_name: grocy
    environment:
      - PUID=1001
      - PGID=33
      - TZ=Europe/Moscow
    volumes:
      - ./config:/config
    expose:
      - 80
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grocy.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.grocy-secure.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.grocy-secure.tls.certresolver=default"
      - "traefik.http.routers.grocy-secure.service=grocy"
      - "traefik.http.services.grocy.loadbalancer.server.port=80"

